# Use a base image with JDK installed
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container
COPY target/BasicjournalApp-0.0.1-SNAPSHOT.jar/app/BasicjournalApp.jar

# Expose the port on which the application runs
EXPOSE 9936

# Command to run the JAR file
CMD ["java", "-jar", "BasicjournalApp.jar"]
